name: upevent
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  googleapis: ^12.0.0
  cupertino_icons: ^1.0.2
  change_app_package_name: ^1.1.0
  rename_app: ^1.3.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  firebase_storage: ^11.6.5
  firebase_database: ^10.4.5
  google_sign_in: ^6.2.1
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  cached_video_player: ^2.0.4
  provider: ^6.1.1
  flutter_markdown: ^0.6.19
  icons_plus: ^5.0.0
  ticket_material: ^0.3.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  qr_flutter: ^4.1.0
  uuid: ^3.0.0
  



dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logomain.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#1c1c1c"
  image: "assets/images/trLogowhite.png"


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/videos/

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

